#!/bin/bash

echo -n "Checking norminette before commit..."
echo "dest" | ./copy_to_subject.sh
if ! norminette dest/ > /dev/null 2> >(cat >&2); then
	echo "❌"
	echo "norminette failed. Commit aborted."
	exit 1
fi
echo "✅"
echo "Build OK. Processing to commit."