# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ttsubo <ttsubo@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/05/03 17:04:43 by ttsubo            #+#    #+#              #
#    Updated: 2025/05/03 17:07:04 by ttsubo           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=philo


all: $(NAME)

$(NAME):
	@echo "TODO"

clean:

fclean:
	$(MAKE) clean

re:
	$(MAKE) fclean
	$(MAKE) all

.PHONY: all clean fclean re
